- name: palybook control using conditions
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx server if redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: install nginx server if debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"