- name: install packages
  hosts: frontend
  become: yes
  tasks:
  - name: install packages one by one
    ansible.builtin.packages:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - mysql
    - zip
    