- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,Suresh,Rajesh,Sai"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Ramesh') }}"

  - name: check names
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}"

  - name: convert map in to list
    vars:
      course:
        name: ansible
        duration: 10hr
        trainer: siva
    ansible.builtin.debug:
      msg: "Course information {{ course | dict2items }}"

  - name: convert list to item
    vars:
      course:
        name: ansible
        duration: 10hr
        trainer: siva
    ansible.builtin.debug:
      msg: "Course information {{ course | items2dict }}"