- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,Suresh,Rajesh,Sai"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Ramesh') }}"

  - name: check names
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}"