- name: user connection
  hosts: local
  connection: local
  tasks:
  - name: check roboshop is exist or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name: create roboshop
    ansible.builtin.command: useradd roboshop
    when: output.rc != 0

  - name: user already exist
    ansible.builtin.debug:
      msg: "user already unnadu"
    when: output.rc == 0